package net.ecsousa.unifivpn.model.unifi

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import tools.jackson.databind.PropertyNamingStrategies
import tools.jackson.databind.annotation.JsonNaming

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
data class NetworkConfig(
    val settingPreference: String?,
    val purpose: String,
    val wanDhcpCos: Int?,
    val wanDhcpv6Cos: Int?,
    val externalId: String,
    val wanTypeV6: String?,
    val routingTableId: Int?,
    val enabled: Boolean?,
    val wanDhcpv6Options: List<String>?,
    val wanDhcpOptions: List<String>?,
    val wanDhcpv6PdSize: Int?,
    val ipv6WanDelegationType: String?,
    val wanDhcpv6PdSizeAuto: Boolean?,
    val wanNetmask: String?,
    val firewallZoneId: String,
    val igmpProxyUpstream: Boolean?,
    val macOverrideEnabled: Boolean?,
    val wanLoadBalanceType: String?,
    val wanFailoverPriority: Int?,
    val ipv6SettingPreference: String?,
    val wanIpv6DnsPreference: String?,
    val wanDns2: String?,
    val singleNetworkLan: String?,
    val wanDns1: String?,
    val wanIpv6Dns1: String?,
    val wanIpv6Dns2: String?,
    val wanNetworkgroup: String?,
    val wanDsliteRemoteHostAuto: Boolean?,
    val wanIpAliases: List<String>?,
    val wanProviderCapabilities: WanProviderCapabilities?,
    val wanSmartqEnabled: Boolean?,
    val wanDnsPreference: String?,
    val wanVlanEnabled: Boolean?,
    val wanLoadBalanceWeight: Int?,
    val siteId: String,
    val name: String,
    val reportWanEvent: Boolean?,
    val wanIp: String?,
    @param:JsonProperty("_id")
    val id: String,
    val attrNoDelete: Boolean?,
    val wanType: String?,
    val attrHiddenId: String?,
    val igmpProxyFor: String?,
    val wanGateway: String?,
    val dhcpdv6DnsAuto: Boolean?,
    val ipv6PdStop: String?,
    val dhcpdGatewayEnabled: Boolean?,
    val ipv6ClientAddressAssignment: String?,
    val dhcpRelayServers: List<String>?,
    val dhcpdStart: String?,
    val dhcpdUnifiController: String?,
    val ipv6RaEnabled: Boolean?,
    val domainName: String?,
    val ipSubnet: String?,
    val ipv6InterfaceType: String?,
    val dhcpdWins2: String?,
    val dhcpdv6Stop: String?,
    val isNat: Boolean?,
    val dhcpdWins1: String?,
    val dhcpdDnsEnabled: Boolean?,
    val internetAccessEnabled: Boolean?,
    val natOutboundIpAddresses: List<String>?,
    val dhcpRelayEnabled: Boolean?,
    val dhcpdConflictChecking: Boolean?,
    val dhcpdWinsEnabled: Boolean?,
    val ipv6PdAutoPrefixidEnabled: Boolean?,
    val dhcpdv6Leasetime: Int?,
    val lteLanEnabled: Boolean?,
    val dhcpdLeasetime: Int?,
    val dhcpguardEnabled: Boolean?,
    val dhcpdTimeOffsetEnabled: Boolean?,
    val dhcpdv6AllowSlaac: Boolean?,
    val ipv6RaPreferredLifetime: Int?,
    val dhcpdStop: String?,
    val dhcpdEnabled: Boolean?,
    val dhcpdWpadUrl: String?,
    val networkgroup: String?,
    val dhcpdv6Start: String?,
    val vlanEnabled: Boolean?,
    val ipv6Aliases: List<String>?,
    val gatewayType: String?,
    val ipv6RaPriority: String?,
    val dhcpdBootEnabled: Boolean?,
    val ipv6PdStart: String?,
    val upnpLanEnabled: Boolean?,
    val dhcpdNtpEnabled: Boolean?,
    val mdnsEnabled: Boolean?,
    val ipAliases: List<String>?,
    val dhcpdTftpServer: String?,
    @param:JsonProperty("dhcpd_user_option_6859c833e94a686382639f59")
    val dhcpdUserOption6859C833E94A686382639F59: String?,
    val autoScaleEnabled: Boolean?,
    val networkIsolationEnabled: Boolean?,
    val igmpSnooping: Boolean?,
    val ipv6PdInterface: String?,
    val vlan: Int?,
    val wireguardInterfaceBindingModeIpVersion: String?,
    @param:JsonProperty("dhcpd_dns_1")
    val dhcpdDns1: String?,
    val xWireguardPrivateKey: String?,
    val interfaceMtuEnabled: Boolean?,
    val vpnType: String?,
    @param:JsonProperty("dhcpd_dns_2")
    val dhcpdDns2: String?,
    val wireguardInterface: String?,
    val wireguardPublicKey: String?,
    val wireguardId: Int?,
    val vpnClientConfigurationRemoteIpOverrideEnabled: Boolean?,
    val localPort: Int?,
    val wireguardLocalWanIp: String?,
    val mssClamp: String?,
    val vpnBindingMode: String?,
    val vpnClientConfigurationRemoteIpOverride: String?,
    val xServerCrt: String?,
    val openvpnLocalWanIp: String?,
    val openvpnInterface: String?,
    val xDhKey: String?,
    val xCaKey: String?,
    val openvpnId: Int?,
    val xSharedClientKey: String?,
    val xServerKey: String?,
    val xAuthKey: String?,
    val xCaCrt: String?,
    val xSharedClientCrt: String?,
    val radiusprofileId: String?,
    val wireguardClientConfigurationFilename: String?,
    val wireguardClientMode: String?,
    val wireguardClientConfigurationFile: String?,
    val wireguardClientPresharedKey: String?,
    val mssClampMss: Int?,
    val wireguardClientPeerPublicKey: String?,
    val wireguardClientPeerPort: Int?,
    val wireguardClientPeerIp: String?,
    val interfaceMtu: Int?,
    val wireguardClientPresharedKeyEnabled: Boolean?,
    val mssClampIpv6: String?,
    val sdwanRemoteSiteId: String?,
    val remoteVpnSubnets: List<String>?,
    val ifname: String?,
    val attrNoEdit: Boolean?,
    val ipv6Subnet: String?,
)

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
data class WanProviderCapabilities(
    val uploadKilobitsPerSecond: Int?,
    val downloadKilobitsPerSecond: Int?,
)